### ISSUE TITLE
Make it available on GitHub Pages

### ISSUE THREAD

**Issue by kpym** [loopspace/jsHobby#1]
You have diverse repos that are "website-ready", having `index.html` coming with `js` and `css` files. 
Proably it is a good idea to activate GitHub Pages on your master branch in "Settings > Options > GitHub Pages > Source : master".

In this way your website will by directly available (no need to download it and open it in local).

**Comment by loopspace** [comment]
I'm sorry -- I missed this comment originally.

I used to publish them via github pages, I have an old version at http://loopspace.github.io/.  I stopped for two reasons: I was using submodules to pull in the individual repositories which was a bit of a pain to maintain, and I wanted to use the sites in a context where typing the first three letters of 'github' was ... problematic!  So I have a site at https://code.mathforge.org where I host my code.

But reading about github pages now, I see that I don't have to use submodules -- it looks like each repository creates its own directory and so the main repository can just be an indexing page.  This would make maintenance simple enough that it's worth doing.  (I'll still keep my off-github site as the primary one since the second reason is still valid.)

Thanks for the suggestion!

**Comment by kpym** [comment]
No problem, good luck with this 🤞

**Comment by loopspace** [comment]
Been a bit of a while, but I finally got round to updating the pages page.  So https://loopspace.github.io/ now includes all my browser-based projects.

**Comment by kpym** [comment]
Fantastic. But it looks like not all links are valid (some projects do not have working pages url), like for example https://loopspace.github.io/TextAnalyser.

**Comment by loopspace** [comment]
Thanks for checking.  Turns out I hadn't enabled pages on all possible projects.  I think it's up to date now.
